# Make sure the PR title adheres to conventional commits format
# See https://www.conventionalcommits.org/en/v1.0.0/#summary

name: 'Check PR Title'
on:
  workflow_call:
jobs:
  conventional-pr-title:
    if: startsWith(github.event.pull_request.title, 'Production Release') == false
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
