name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  # Make sure the PR title adheres to conventional commits format
  pr-title:
    uses: ./.github/workflows/check-pr-title.yaml
    secrets: inherit

 
  # Summary job that aggregates all CI results
  required:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - pr-title
    steps:
      - run: |
          echo "Job statuses:"
          echo "pr-title: ${{ needs.pr-title.result }}"

          # Check if any required job failed
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]; then
            echo "❌ One or more jobs failed"
            exit 1
          else
            echo "✅ All relevant jobs completed successfully"
          fi
