name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited]

permissions:
  statuses: write
  pull-requests: read

jobs:
  # Make sure the PR title adheres to conventional commits format
  pr-title:
    if: github.event.action == 'edited' || github.event.action == 'opened' || github.event.action == 'reopened'
    uses: ./.github/workflows/check-pr-title.yaml
    secrets: inherit

 
  # Test job that should NOT run on edited events
  test-job:
    runs-on: ubuntu-latest
    if: github.event.action != 'edited'
    steps:
      - run: echo "This job runs on non-edit events only"

  # Summary job that aggregates all CI results
  required:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - pr-title
      - test-job
    steps:
      - run: |
          echo "Job statuses:"
          echo "pr-title: ${{ needs.pr-title.result }}"
          echo "test-job: ${{ needs.test-job.result }}"

          # Check if any required job failed
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]; then
            echo "❌ One or more jobs failed"
            exit 1
          else
            echo "✅ All relevant jobs completed successfully"
          fi
